/**
 * AiDisclosureBanner
 *
 * Per CONSTITUTION § 4 — Transparent AI Disclosure:
 *   - Must be visible at all times when viewing AI-generated output
 *   - Must NOT be permanently dismissible
 *   - Users must acknowledge before saving/exporting
 */

import React from 'react';
import './AiDisclosureBanner.css';

interface Props {
  acknowledged: boolean;
  onAcknowledge: () => void;
}

export const AiDisclosureBanner: React.FC<Props> = ({
  acknowledged,
  onAcknowledge,
}) => {
  return (
    <div
      className={`ai-banner ${acknowledged ? 'ai-banner--acknowledged' : 'ai-banner--pending'}`}
      role="alert"
      aria-live="polite"
    >
      <span className="ai-banner__icon">⚠️</span>
      <span className="ai-banner__text">
        <strong>AI-Generated Content</strong> — This Table of Contents was
        generated by AI and may not be accurate. Always verify before use.
      </span>
      {!acknowledged && (
        <button
          className="ai-banner__ack-btn"
          onClick={onAcknowledge}
          aria-label="Acknowledge AI-generated content warning"
        >
          I understand
        </button>
      )}
      {acknowledged && (
        <span className="ai-banner__ack-label" aria-label="Warning acknowledged">
          ✓ Acknowledged
        </span>
      )}
    </div>
  );
};
